---
title: "Homework 2"
output: html_document
---

I'm an R Markdown document! 

# Problem 1

```{r}
library(tidyverse)
library(readxl)
```
```{r}
pols_df = read_csv("./fivethirtyeight_datasets/fivethirtyeight_datasets/pols-month.csv")
snp_df = read_csv("./fivethirtyeight_datasets/fivethirtyeight_datasets/snp.csv")
unemployment_df = read_csv("./fivethirtyeight_datasets/fivethirtyeight_datasets/unemployment.csv")
```

```{r}

separate_pols_df =
  
  separate(pols_df, mon, into = c("Year", "month", "day"), sep = "-")

integer_pols_df =
  mutate(separate_pols_df,
         Year = strtoi(Year),
         month = strtoi(month),
         day = strtoi(day))

month_name_pols_df = 
  mutate(integer_pols_df, month = month.abb[month])

president_pols_df = mutate(month_name_pols_df, 
                           president = case_when(
                             prez_dem == 1 ~ "gop",
                             prez_gop == 1 ~ "dem"
                           ))

clean_pols_df = select(president_pols_df, -day, -prez_dem, -prez_gop)

```

```{r}
separate_snp_df =
  
  separate(snp_df, date, into = c("Year", "month", "day"), sep = "-")

integer_snp_df =
  mutate(separate_snp_df,
         Year = strtoi(Year),
         month = strtoi(month),
         day = strtoi(day))

month_name_snp_df = 
  mutate(integer_snp_df, month = month.abb[month])

clean_snp_df = select(month_name_snp_df, -day)

arranged_snp_df = arrange(clean_snp_df, Year, month)
```

```{r}
pivot_unemployment_df = 
  pivot_longer(
    unemployment_df, Jan:Dec, 
    names_to = "month",
    values_to = "unemployment_rate"
  )

clean_unemployment_df = arrange(pivot_unemployment_df, Year, month)
```

```{r}
first_merged_df = left_join(clean_pols_df , arranged_snp_df, by = c("Year", "month"))
final_merged_df = left_join(clean_unemployment_df, first_merged_df, by = c("Year", "month"))

final_merged_df
```

#problem 2

```{r}
mr_trash_wheel_df = read_excel("./fivethirtyeight_datasets/202509 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N710")

mr_trash_wheel_omit_df = drop_na(mr_trash_wheel_df, Dumpster)

almost_mr_trash_wheel_df = mutate(mr_trash_wheel_omit_df, `Sports Balls` = as.integer(round(`Sports Balls`, 0)))

without_name_mr_trash_wheel_df = mutate(almost_mr_trash_wheel_df, Year = as.integer(Year))

clean_mr_trash_wheel_df = mutate(without_name_mr_trash_wheel_df, Sheet = "Mr. Trash Wheel")
```

```{r}
professor_trash_wheel_df = read_excel("./fivethirtyeight_datasets/202509 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M135")

professor_trash_wheel_omit_df = drop_na(professor_trash_wheel_df, Dumpster)

without_professor_trash_wheel_df = mutate(professor_trash_wheel_omit_df, Year = as.integer(Year))

clean_professor_trash_wheel_df = mutate(without_professor_trash_wheel_df, Sheet = "Professor Trash Wheel", `Sports Balls` = NA)
```

```{r}
Gwynnda_trash_wheel_df = read_excel("./fivethirtyeight_datasets/202509 Trash Wheel Collection Data.xlsx", sheet = "Gwynns Falls Trash Wheel", range = "A2:L352")

Gwynnda_trash_wheel_omit_df = drop_na(Gwynnda_trash_wheel_df, Dumpster)

without_Gwynnda_trash_wheel_df = mutate(Gwynnda_trash_wheel_omit_df, Year = as.integer(Year))

clean_Gwynnda_trash_wheel_df = mutate(without_Gwynnda_trash_wheel_df, Sheet = "Gwynns Falls Trash Wheel", `Sports Balls` = NA, `Glass Bottles` = NA)
```

```{r}
merged_data_trash_wheel_1 = bind_rows(clean_mr_trash_wheel_df, clean_professor_trash_wheel_df, clean_Gwynnda_trash_wheel_df)

merged_data_trash_wheel_final = select(merged_data_trash_wheel_1, Sheet, everything())

merged_data_trash_wheel_final
```

# Problem 3

```{r}
zillow_price_df = read_csv("./zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv")
zillow_price_zip_variation_df = mutate(zillow_price_df, ZipCode = RegionName)
zillow_clean_price_df = select(zillow_price_zip_variation_df, -`StateName`, -RegionName, -RegionType)

zillow_clean_price_df
```

```{r}
zillow_df = read_csv("./zillow_data/Zip Codes.csv")
zillow_county_variation_df = mutate(zillow_df, CountyName = paste(County, "County"))
zillow_clean_df = select(zillow_county_variation_df, -`State FIPS`, -`County FIPS`, -County)
zillow_clean_df
```

```{r}
first_single_zillow_df = left_join(zillow_clean_df, zillow_clean_price_2_df)
first_clean_single_zillow_df = arrange(first_single_zillow_df, RegionID)

unique_zip_codes = length(unique(first_clean_single_zillow_df$ZipCode))
unique_neighborhoods = length(unique(first_clean_single_zillow_df$Neighborhood))

print(unique_zip_codes)
print(unique_neighborhoods)

first_clean_single_zillow_df

```

```{r}
single_zillow_df = left_join(zillow_clean_price_df, zillow_clean_df)
rental_price_zillow_df = mutate(single_zillow_df, `Rental Difference 2021 vs 2020` = `2021-01-31` - `2020-01-31`)

clean_zillow_single_df = arrange(rental_price_zillow_df, `Rental Difference 2021 vs 2020`)
arranged_zillow_df = select(clean_zillow_single_df, `RegionID`, SizeRank, ZipCode, State, City, CountyName, `County Code`, Neighborhood, Metro, `Rental Difference 2021 vs 2020`, `2020-01-31`, `2021-01-31`)

arranged_zillow_df

dataframe_price_drop = select(arranged_zillow_df, ZipCode,Neighborhood, `Rental Difference 2021 vs 2020`)
price_drop_table = slice_head(dataframe_price_drop, n= 10)
print(price_drop_table)
```